[package]
name = "rusty-navigator"
version = "0.1.0"
authors = ["doublescale <doublescale@tutanota.com>"]
edition = "2018"
license = "MIT"

[dependencies]
rand = "0.7.3"
sdl2 = { version = "0.32", features = ["image"] }
